### ISSUE TITLE
If harpoon restarts all items are redeployed

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#116]
As a harpoon user, in the event that Harpoon restarts I shouldn't need to completely redeploy assets all over again. I should see that the directory exists and know I need to do a pull and execute the pull code.

**Comment by josephsawaya** [comment]
If the state of pods and containers on the host machine changes while Harpoon is down, would we want there to be some reconciliation?

**Comment by cooktheryan** [comment]
I think we would expect that the admin of the cluster would patch the system and update the code within Git. One of the expectations of GitOps is that these systems aren't really interacted with by hand. 

In one of those type of scenarios we would expect Harpoon to start back up look to see if there is a pull to do and based off the current function it would then attempt to do the deploy but only if there was something to pull.


This is an interesting problem because we have two sides of it. It would be nice if all of the containers were down because of a situation on the host that Harpoon would attempt to revive them upon startup. Also, if someone made manual changes while Harpoon was down we would hope they would populate that change to git.

**Comment by josephsawaya** [comment]
Ok, so `applyInitial()` should only run if the directory does not exist?

**Comment by cooktheryan** [comment]
@josephsawaya I definitely want to talk about it. Initially in my head I want to say "yea only run if directory does not exist" but you have me questioning it based on a host reboot. This may require some testing to see what the impact of rebooting a host that has raw and kube containers deployed to see if they come up on their own at boot

**Comment by cooktheryan** [comment]
This is acceptable
