### ISSUE TITLE
Keep Harpoon running

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#119]
As a harpooner, I would like that Harpoon would keep running and just print errors rather than exit and stop the harpoon service.

AC:
- Verify harpoon starts and keeps running even if a method has an error

**Comment by sallyom** [comment]
@josephsawaya @cooktheryan if it's ok, I've started working on this, i'm assigning it to myself for now - @josephsawaya if you've already started on it, we'll work together :) it'll be co-authored
