### ISSUE TITLE
Harpoon configuration file from URL or Git

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#120]
As a harpooner, I would like to be able to have my configuration file stored remotely and be able to be pulled down so that I don't have to place it on the system.

AC:
Verify a configuration file can be loaded from a remote location and harpoon runs

**Comment by sallyom** [comment]
This is what I'm thinking:
The local config.yaml _only_ contains urls to repositories.
To opt-in, a listed repository has a .`/.harpoon/harpoon.yaml`. From the list of repositories, harpoon will fetch the config file from the repository and will merge them into the HarpoonConfig. also (maybe?) harpoon will write the merged config at ~/.harpoon/harpoon.yaml
