### ISSUE TITLE
Define json for file delivery proposal

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#14]
As a coder, I would like to define what the parameters would look like to define how a file can be taken from an image and placed on the system.

AC:
Verify a destination path is provided
Verify subsequent enhancement tasks are opened after the fact

**Comment by cooktheryan** [comment]
talking with @sallyom we could reuse a lot of the systemd work

**Comment by cooktheryan** [comment]
@sallyom @josephsawaya 

I'm thinking of introducing something like this

```
{"Url":"http://github.com/cooktheryan/harpoon",
"Subdirectory": "examples/ansible",
"Branch":"ansible",
"Method":"ansible",
"Schedule": "*/1 * * * *",
"MethodVariables": [
    {
    "ansible_config": "~/ansible.cfg",
    "ssh_key": "~/.ssh/id_rsa"
}]
}
```

Specifically the MethodVariables section. This would allow for us for the file delivery to specify a Deployment directory, systemd directory location, for ansible allow us to pass ssh keys etc, and so on. These items would be items that we necessarily wouldn't be frequently changing compared to those items we would be trying to deploy.

Thoughts?

**Comment by cooktheryan** [comment]
@RobotSail not sure if you have any thoughts on the above json in general

**Comment by RobotSail** [comment]
@cooktheryan The `subdirectory` property is a good addition. Only thing I would change is have MethodVariables be an object rather than a list of objects, unless there's some reason for this being the case.

**Comment by cooktheryan** [comment]
@RobotSail I was thinking with `MethodVariables` it will be almost a catch all for some required variables for different methods. So the above is some ansible MethodVariables others may include

For systemd
```
"MethodVariables": [
   {"systemdDirectory": "/etc/systemd/system"
   }]
 ```
 
 For file
 ```
"MethodVariables": [
   {"destinationDirectory": "/var/lib/dinosaur",
   "owner": "root",
   "mode": "0600"
   }] 
 ```

**Comment by cooktheryan** [comment]
closing in favor of @sallyom work
