### ISSUE TITLE
When using Raw pull the new image first then stop the existing container

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#141]
As a harpooner using raw, I would like to pull the new image first before stopping the existing container. This could allow for me to only be out of business for only moments vs needing to pull an image.

**Comment by josephsawaya** [comment]
Does this do what you're talking about: https://github.com/redhat-et/harpoon/blob/main/pkg/engine/raw.go#L98

**Comment by cooktheryan** [comment]
@josephsawaya yea. I think Its just going to be a simple reordering thing. Move the container deletion down and the detectorFetchImage up
