### ISSUE TITLE
what happens if two mechanisms are used or if multiple different harpoons are defined

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#48]
As a harpoon user, I need to test the possibility of defining multiple directories and methods to see what happens and what sort of fixes need to occur.

AC:
Verify two different methods can be defined in a json
Verify two different directories can be defined in json

**Comment by cooktheryan** [comment]
Cannot currently define multiple harpoon items

**Comment by sallyom** [comment]
in the Repo type, maybe a 
map[string]string 
of key, value == method, fileLocation (subDir or single file)
Then process can loop thru all
