### ISSUE TITLE
DRY the processMethod functions

### ISSUE THREAD

**Issue by sallyom** [redhat-et/harpoon#81]
There is a lot of repeated code that can be refactored in harpoon.go (from me, I repeated the code :) )

@josephsawaya i believe you're looking into pulling out the initialRun logic into a fn? If not let me know, I'll assign to myself.

**Comment by josephsawaya** [comment]
I did part of this in my latest PR: #86 

I think there's more code that can be pulled out into a function, I can get that done in my next PR

**Comment by sallyom** [comment]
@josephsawaya if you're ok w/ this, you can close this issue - your PR resolved this, imo! https://github.com/redhat-et/harpoon/pull/91

**Comment by josephsawaya** [comment]
This one should be good for now!
