### ISSUE TITLE
Kube pods with same name leads to unwanted behaviour

### ISSUE THREAD

**Issue by josephsawaya** [redhat-et/harpoon#84]
Currently if there are two pod specs with the same name, harpoon will play them one by one, but tear down the previous one without any indication of this happening. This could be avoided by just having a different name for each pod, but that's sort of inelegant and I'm thinking it would be a good idea to have checks in the code to make sure a user does not break things accidentally. I can't think of a simple way to solve this problem with the way the code is structured right now so ideas are welcome, but also let me know if I shouldn't worry about it and that I should just document it.

**Comment by cooktheryan** [comment]
resolved with this line https://github.com/redhat-et/harpoon/blob/main/pkg/engine/kube.go#L181
